<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OndeVaiPassar.Domain\OndeVaiPassar.Domain.csproj" />
    <ProjectReference Include="..\OndeVaiPassar.DTOs\OndeVaiPassar.DTOs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Venues\" />
  </ItemGroup>

</Project>
