<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OndeVaiPassar.Domain\OndeVaiPassar.Domain.csproj" />
    <ProjectReference Include="..\OndeVaiPassar.Persistence\OndeVaiPassar.Persistence.csproj" />
    <ProjectReference Include="..\OndeVaiPassar.QueryStore\OndeVaiPassar.QueryStore.csproj" />
    <ProjectReference Include="..\OndeVaiPassar.Query\OndeVaiPassar.Query.csproj" />
  </ItemGroup>

</Project>
